export const VIDEOS_ACTIONS = {
  INITIALIZE_VIDEOS: 'INITIALIZE_VIDEOS',
  INITIALIZE_VIDEOS_DATA: 'INITIALIZE_VIDEOS_DATA',
  UPDATE_HISTORY: 'UPDATE_HISTORY',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  UPDATE_PLAYLISTS: 'UPDATE_PLAYLISTS',
  RESET_VIDEOS_DATA: 'RESET_VIDEOS_DATA',
};
